### ISSUE TITLE
Cityscapes format instance annotations

### ISSUE THREAD

**Issue by txfs1926** [CAPTAIN-WHU/iSAID_Devkit#11]
Hi, thanks for this great dataset!

I've noticed that the ground truth are in RGB format. Could you provide some instructions to convert the annotations into Cityscapes-format, like the ground truth `_gtFine_instanceIds.png` where instances are annotated with class_id * 1000 + instance_id?

Thank you very much!

**Comment by akshitac8** [comment]
Hi, @txfs1926 You can use the reference coco_convertion file to convert the dataset to Cityscapes format.

**Comment by isolution911** [comment]
> 
> 
> Hi, @txfs1926 You can use the reference coco_convertion file to convert the dataset to Cityscapes format.
Sorry, I don't understand which file is the reference coco_convertion file? I also want to convert the annotations into cityscapes-format.
