### ISSUE TITLE
Can you provide the corresponding relationship between category and color?

### ISSUE THREAD

**Issue by txfs1926** [CAPTAIN-WHU/iSAID_Devkit#12]
Hi, I cannot find the relationship between category and the RGB color of each semantic label. Could you provide it? Thanks!

**Comment by akshitac8** [comment]
hi @txfs1926 
You can find the relationship between the category and colour in this file:
https://github.com/CAPTAIN-WHU/iSAID_Devkit/blob/master/preprocess/cityscapesScripts/cityscapesscripts/helpers/labels.py
