### ISSUE TITLE
安装过程中的错误

### ISSUE THREAD

**Issue by kaijieshi7** [CAPTAIN-WHU/iSAID_Devkit#15]
![Screenshot from 2020-06-09 20-05-57](https://user-images.githubusercontent.com/19171201/84145802-21a82600-aa8d-11ea-851a-f8da66d840d1.png)
第一步conda env create -f environment.yml就出错了，请问您碰到多这种情况吗？

**Comment by kaijieshi7** [comment]
sudo apt-get install cmake build-essential libjpeg-dev libpng-dev
this maybe useful!!!

**Comment by gewenchao** [comment]
> sudo apt-get install cmake build-essential libjpeg-dev libpng-dev
> this maybe useful!!!

thank you,this is very useful !
