### ISSUE TITLE
Can the instance-annotated json file be shared?

### ISSUE THREAD

**Issue by aiarjun** [CAPTAIN-WHU/iSAID_Devkit#16]
Downloading all the images(train, validation and test) spans almost 25 GB In my local drive. It is said that downloading the images are required to create the COCO-style annotations. **Can you please share the COCO-annotations directly** so that I can use it directly in an online platform like Google Colab without having to go through the Conda environment creation, preprocessing, etc?

**Comment by akshitac8** [comment]
Hi, @aiarjun For training the model you will need both annotations and images. So, Even if we share the annotations you will still have to download the images :)

**Comment by aiarjun** [comment]
Yes, but I do not have to create a Conda environment, and get the files in the format given in README.md. I could directly get images, and annotations and train a model, and evaluate.

**Comment by aiarjun** [comment]
Can you please share the files? I do not have an offline GPU and I have a Google Cloud which can store all the images, but does not have support for Anaconda.
