### ISSUE TITLE
Mapping from semantic segmentation to class names

### ISSUE THREAD

**Issue by tmensink** [CAPTAIN-WHU/iSAID_Devkit#18]
I cant find the mapping from the segmentation colours used:

`[  0,   0, 127],
  [  0,  63,  63],
  [  0, 127, 127],
  [  0, 127, 255]`
to the semantic classes (airplane, grass, ...). Where can I find these?

**Comment by akshitac8** [comment]
Hi @tmensink,
You can find the colour mapping in this file -> https://github.com/CAPTAIN-WHU/iSAID_Devkit/blob/f2b9197a53c27383463fd8911facc7f71b96dc79/preprocess/cityscapesScripts/cityscapesscripts/helpers/labels.py

**Comment by akshitac8** [comment]
@tmensink Is your issue solved?

**Comment by tmensink** [comment]
Yes. Thanks for asking.
