### ISSUE TITLE
How to drop  small clipped label When split image into patches?

### ISSUE THREAD

**Issue by lyw615** [CAPTAIN-WHU/iSAID_Devkit#19]
After running the split.py, many label are clipped with low area, which confused the network and  influences the convergence process. Are there any  solution to save the clipped label with proportion  of original area?

**Comment by akshitac8** [comment]
Hello @lyw615 can you specify the meaning of low area? for saving the clipped label with the proportion of original area you can make changes to the original split.py file to make sure the original data is saved before clipping.

**Comment by akshitac8** [comment]
Hello @lyw615 Is the issue solved?
