### ISSUE TITLE
run python preprocess.py --set train,val error!

### ISSUE THREAD

**Issue by gm0515** [CAPTAIN-WHU/iSAID_Devkit#2]
Starting train
./dataset/iSAID_patches/train/images
Processed 0 images, 0 annotations
Processing Image P0000_0_800_0_800.png
Processing Image P0000_0_800_0_800.png
Processing 1 images...
Processing 1 images...
Segment file: ./dataset/iSAID_patches/train/images/P0000_0_800_0_800_instance_color_RGB.png
Instance files: ./dataset/iSAID_patches/train/images/P0000_0_800_0_800_instance_id_RGB.png
Traceback (most recent call last):
  File "preprocess.py", line 156, in <module>
    convert_cityscapes_instance_only(args.datadir, args.outdir)
  File "preprocess.py", line 110, in convert_cityscapes_instance_only
    objects = cs.instances2dict_with_polygons([seg_fullname],[inst_fullname], verbose=True)
  File "/media/zheng/DATA1/gm/222222/iSAID_Devkit-master/preprocess/cityscapesScripts/cityscapesscripts/evaluation/instances2dict_with_polygons.py", line 76, in instances2dict_with_polygons
    instanceObj = Instance(imgNp,imgNp_seg, instanceId)
TypeError: __init__() takes 3 positional arguments but 4 were given

How to solve it,thanks!

**Comment by akshitac8** [comment]
@gm0515 Is the issue solved?

**Comment by txfs1926** [comment]
same here

**Comment by txfs1926** [comment]
Resolved. Use the cityscapesScripts provided by this repo instead of pip install the lastest version of that.

**Comment by jamesbc123** [comment]
I am using cityscapesScripts version 1.0.8, which I think is the one used by this repo. But I get the same error : TypeError: init() takes 3 positional arguments but 4 were given

**Comment by jamesbc123** [comment]
> I am using cityscapesScripts version 1.0.8, which I think is the one used by this repo. But I get the same error : TypeError: init() takes 3 positional arguments but 4 were given

I would really appreciate a response. Thanks!
