### ISSUE TITLE
Create coco-format json annotation files error

### ISSUE THREAD

**Issue by RaagaMadappa** [CAPTAIN-WHU/iSAID_Devkit#22]
Hi Team, 

I have followed all the steps exactly as given in the readme file and I am getting an error in the "Create coco-format json annotation files for train and val split images python preprocess.py --set train,val" step." : 
 Error in `python': free(): invalid pointer: 0x00007faf52d88440 ***
and there is a long back trace. 
The error is coming from the "import cityscapesScripts.cityscapesscripts.evaluation.instances2dict_with_polygons as cs" statement and within that the error is coming from "import lycon"
My system is Ubuntu 16.04.7 and I am using the conda environment which i created from the .yml file provided. 
Do you have any suggestions on how to resolve this issue?

Thank you

**Comment by akshitac8** [comment]
Hi, @RaagaMadappa Thank you for your interest in our work.
Did you try this -> sudo apt-get install cmake build-essential libjpeg-dev libpng-dev
