### ISSUE TITLE
Got "Warning: invalid contours" while creating json annotation files using preprocess.py file

### ISSUE THREAD

**Issue by vineel96** [CAPTAIN-WHU/iSAID_Devkit#24]
@akshitac8 Hi,
I'm getting "Warning: invalid contours" on some images while creating json annotation files. Should we ignore those images or any other way to resolve it? (please check screenshot attached)
Thanks
![image](https://user-images.githubusercontent.com/16516666/114058241-eb0b8980-98b0-11eb-983f-d5302f9ef8ef.png)

**Comment by akshitac8** [comment]
You can ignore the warning they come for a few objects within the image. It's nothing to worry about.
