### ISSUE TITLE
What is the difference between these two Jsons

### ISSUE THREAD

**Issue by Kismetzc** [CAPTAIN-WHU/iSAID_Devkit#26]
![2021-05-11_213007](https://user-images.githubusercontent.com/52264144/117823799-72795d80-b2a0-11eb-8d37-f0f65b3181fb.png)

**Comment by akshitac8** [comment]
Hello @Kismetzc, Please use the train json with 325.6M size.

**Comment by Kismetzc** [comment]
Yeah.

And I found that the iSAID_train file is missing images of the Harbor category and the iSAID_train_20190823_114751 file is missing height and width information. 

Does the missing width and height information of the image affect the result?

**Comment by akshitac8** [comment]
@Kismetzc Yes for data preparation details are mentioned in the readme.

**Comment by Kismetzc** [comment]
> @Kismetzc Yes for data preparation details are mentioned in the readme

> @Kismetzc Yes for data preparation details are mentioned in the readme.

**Comment by Kismetzc** [comment]
> @Kismetzc Yes for data preparation details are mentioned in the readme.

OK，THX

I will do data preparation later!

**Comment by Kismetzc** [comment]
I got the right format json file after data preparation!
Thank you!
Maybe you could explain that the file for download is not complete！
![data_exploration](https://user-images.githubusercontent.com/52264144/118134464-8950b900-b434-11eb-865d-867b5f5d5c33.png)
