### ISSUE TITLE
how to get correct test json

### ISSUE THREAD

**Issue by violetyamazakura** [CAPTAIN-WHU/iSAID_Devkit#36]
i processed my dataset using iSAID_Devkit and got a test json using my algorithm, and i had tested my val.json using evaluate.py, but when i upload my test.json to the server(or even val.json or examples downloaded from server)， the e-mail told me there's something wrong with my submission. my test json and val json have same format with examples, i don't know what's wrong with my submission.
![image](https://github.com/CAPTAIN-WHU/iSAID_Devkit/assets/52644318/51aba9ad-f204-4f02-8a4a-3b7f99680598)
![image](https://github.com/CAPTAIN-WHU/iSAID_Devkit/assets/52644318/99efd2a6-9f88-49f6-aa3b-db6c523e29f3)

**Comment by zxw223311** [comment]
hello, how can you run preprocess.py?thanks

**Comment by violetyamazakura** [comment]
thank you for you reply, i've found my mistake and i can make correct test file now.
