### ISSUE TITLE
Werid resolution after process with iSAID_devkit

### ISSUE THREAD

**Issue by GitHberChen** [CAPTAIN-WHU/iSAID_Devkit#6]
Hello, Our lab (in Beijing Institute of Technology) is trying do some researh on iSAID dataset, but encounter a problem: when I have downloaded and done pre-process with dev-kit, the most of picture is 800x800, which is fine with training and testing. however, resolution of some picture is quit werid, like 1563x558, 1314x582, 6402x525. Is this normal? I think both side of pic patches should smaller than 800. And, should I predict on this pic patch with werid resolution before upload to evaluate server? It may not fit into the memory of Graphic card.

**Comment by akshitac8** [comment]
@GitHberChen yes, the image sizes are normal. you will first need to create patches of all the images with size greater than 800. For that, you need to follow the readme for preprocessing the data.

**Comment by akshitac8** [comment]
@GitHberChen is the problem solved??

**Comment by GitHberChen** [comment]
> @GitHberChen is the problem solved??

Yes，I solved this problem, thanks a lot

**Comment by akshitac8** [comment]
No problem @GitHberChen
