### ISSUE TITLE
Does this script only use top 100 detections for evaluation？

### ISSUE THREAD

**Issue by GitHberChen** [CAPTAIN-WHU/iSAID_Devkit#8]
Does this script only use top 100 detections for evaluation？Though majority of images in dataset only have less than 100 objects, some of them have more 1,000. and, how many detections  does evaluation server use? 100?

**Comment by akshitac8** [comment]
@GitHberChen if you want to reproduce the numbers mentioned in the paper then the evaluation script uses top 1000 detection boxes as most of the images have more than 1000 objects.

**Comment by akshitac8** [comment]
@GitHberChen is the issue solved?
