### ISSUE TITLE
How could I get AP result on iSAID test set?

### ISSUE THREAD

**Issue by GitHberChen** [CAPTAIN-WHU/iSAID_Devkit#9]
Hello, I’m doing some experiments on iSAID, I uploaded instance_result.zip to[ server](http://117.78.28.204:8006/evaluation1/) several times, but can not get my result. I click result with Chrome on my MacBook but can only see **The table can only be shown on chrome now**. I'm really confused. How could I get AP result on test set? 

Thanks a lot.

**Comment by GitHberChen** [comment]
And as long as  I uploaded  instance_result.zip to server, I find the server won't response anymore...

**Comment by ztyxd** [comment]
@GitHberChen 

Do you get your result on test set?
I have submitted my JSON file into the evaluation system but the email say that:
         There is something wrong with your submission as follows:

          You can submit standard formatted results again.

**Comment by akshitac8** [comment]
Yes, @ztyxd we have our results on the test set. Did you generate the test results in the format mentioned in Devkit?

**Comment by ztyxd** [comment]
@akshitac8 Thank you for your reply.

I first use split.py to get the patches of the test image, then use  test_image_ids_json.py to get the test.json file.  After these two preprocess I test my model on the above image patches and json file, and get the predict json file. When I submit the test set to the submission server, the submission server says that my submission format is wrong.

It is worth noting that I can get the results of the verification set locally through the evaluate.py

**Comment by akshitac8** [comment]
@ztyxd Were you able to get results on validation data?

**Comment by akshitac8** [comment]
[test_info.json.zip](https://github.com/CAPTAIN-WHU/iSAID_Devkit/files/4585826/test_info.json.zip)
@ztyxd You can confirm your test data format using this file.

**Comment by ztyxd** [comment]
@akshitac8 
Sorry, it was my own mistake that caused the submission format to be incorrect.
Thank you for your serious reply.

**Comment by akshitac8** [comment]
@ztyxd Were you able get results on the test set?

**Comment by lyw615** [comment]
> [test_info.json.zip](https://github.com/CAPTAIN-WHU/iSAID_Devkit/files/4585826/test_info.json.zip)
> @ztyxd You can confirm your test data format using this file.

Why there is no annotation information in it ?

**Comment by akshitac8** [comment]
@lyw615 you can get results on the test set using the evaluation server.

**Comment by lyw615** [comment]
> @lyw615 you can get results on the test set using the evaluation server.
What‘s   the input and output of the evaluation server?   Do you mean get input my infer json and true groudth json then get score?  Or get json file from the inferred mask?

**Comment by akshitac8** [comment]
@lyw615 The test server is your test prediction json and the output will be mean average precision

**Comment by akshitac8** [comment]
@lyw615 Were you able to get results from the evaluation server?

**Comment by ZZR8066** [comment]
> I first use split.py to get the patches of the test image, then use test_image_ids_json.py to get the test.json file. After these two preprocess I test my model on the above image patches and json file, and get the predict json file. When I submit the test set to the submission server, the submission server says that my submission format is wrong.

I take the same process "I first use split.py to get the patches of the test image, then use test_image_ids_json.py to get the test.json file. After these two preprocess I test my model on the above image patches and json file, and get the predict json file." as you mentioned above.  But when I submit the predict json file to  the evaluation system, the email says that:
"You can submit standard formatted results again."
Could you tell me how you solved it in the end
